import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { ThemeProvider } from "@/components/common/theme-provider"
import "./globals.css";
import { cookies } from "next/headers"
import { ToastContainer} from 'react-toastify';

import { AppSidebar } from "@/components/common/app-sidebar";


export const metadata: Metadata = {
  title: "پوپکد",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"
 

  return (
    <html lang="fa" dir='rtl' suppressHydrationWarning>
      <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            >
            <SidebarProvider defaultOpen={defaultOpen}>
              <AppSidebar />
              <SidebarTrigger />
              <main className="flex h-screen w-full items-center justify-center"> 
                
                {children}
              
              </main>
                
            <ToastContainer />
        </SidebarProvider>
      </ThemeProvider>
      </body>
    </html>
  );
}
