# Generated by Django 5.2 on 2025-06-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="level_user",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="score",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
